FROM maven:3.9.8-eclipse-temurin-21

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

EXPOSE 8080

ENV TZ=Asia/Kolkata \
    SPRING_PROFILES_ACTIVE=dev

ENTRYPOINT ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
