spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.vyaparsetu: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

server:
  port: 8080
